### ISSUE TITLE
Tests?

### ISSUE THREAD

**Issue by rwjblue** [heimdalljs/heimdall-fs-monitor#5]
This is somewhat related to #4 (I looked for tests to figure out what it does 😈 )..

**Comment by Turbo87** [comment]
@rwjblue does https://github.com/heimdalljs/heimdall-fs-monitor/pull/10 qualify as "tests"?

**Comment by rwjblue** [comment]
Ya, but we should probably add more.

**Comment by hjdivad** [comment]
> @rwjblue does #10 qualify as "tests"?

barely ^_^
